version: '3'

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres
    env_file: .docker-env
    volumes:
      - db-data:/var/lib/postgresql/db-data

  mail:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

  app:
    build: .
    env_file: .docker-env
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - db
      - mail
